### ISSUE TITLE
[Feature Request] Enable zPIV automint value to 0 to disable autominting

### ISSUE THREAD

**Issue by StrontiumZ38** [PIVX-Project/PIVX#581] opened 2018-04-25 13:00 UTC
### Describe the issue
For the sake of usability, clarity, and foolproofing zPIV Automint options, user can disable (and visually uncheck) 'Enable zPIV Automint' by pressing the down arrow, or entering 0 in percentage field.
### Can you reliably reproduce the issue?
Yes
#### If so, please list the steps to reproduce below:
1. Check zPIV Automint tickbox
2. Set zPIV Automint percentage value to 1
3. Press down arrow on percentage value OR alternatively enter 0 as a value

### Expected behavior
Tickbox and associated behaviour are triggered as if the tickbox was manually clicked, reinforcing a parity between tickbox and percentage field to user.

### Actual behavior
Tickbox remains master, with user entry being ignored (click) or reverted (integer entry) when the value is below 1.

### Screenshots.
![req](https://user-images.githubusercontent.com/38264865/39247130-84937b98-48d3-11e8-8256-077eef7ca91f.png)

### What version of PIVX Core are you using?
Dev build - 3.1.0 pre-release

**Comment by rejectedpromise** [comment] 2018-05-09 00:57
Unchecking the box should disable automint all together, regardless of the percentage selected was.
Is there a reason for setting it to 0 other than disabling?

**Comment by h0wXD** [comment] 2018-05-09 01:07
I think we should keep the check box and validate if the value is valid > 0 && <= 100? I don't think we should be adding in some UI flow hack just to uncheck a checkbox when the user enters the value zero.

**Comment by rejectedpromise** [comment] 2018-05-09 01:29
@h0wXD
0 is an invalid _percentage of autominted zpiv_

If you want to avoid the _UI flow hack_ simply set the options in pivx.conf like so:
`enablezeromint = 0`
`zeromintpercentage = <doesn't matter when disabled>`

or provide them as flags from the cli

**Comment by PIVXStrontium** [comment] 2018-05-14 06:00
Everything you guys are saying is completely logical, of course. The issue is that users often are not, so this suggestion was towards idiot-proofing.

An alternative could be to grey out or even disable entry to the field while checkbox is unchecked, or simply add a note to the percent option (only applies if automint enabled).

**Comment by Fuzzbawls** [comment] 2019-01-18 10:37
revisiting this:

I don't agree with making the percentage input have any effect on the "master" toggle. That said, I do think that it would be good to provide more strict validation of the percentage input here.

Currently, if someone enters `0` and presses the `OK` button, no warning/error is given and the percentage just silently reverts to `10`, which I could see as causing undue confusion.

**Comment by Mrs-X** [comment] 2019-01-20 20:50
When you enter a `0` and click on any active control (e.g. the "Enable zPIV Automint" checkbox) you'll see that the value is reverted to the value it had before.

This is because the underlying Qt object (which is a `QSpinBox`) has a minimum (= `0`) and a maximum (= `100`) property defined which automatically reverts the value if it's outside the predefined range.

When you click the "OK" button (or just hit "Enter") the same happens, but you won't notice it because it happens too fast.

To have a warning-popup here we would have to disable this standard Qt-feature and implement our own input-validator.
That's possible of course, but I don't think the small increase in usability would be worth the efforts.

**Comment by Carbon-Zero** [comment] 2019-03-03 21:14
I think the current flow makes as much sense as the alternate flow.  You're just switching which one overrides the other.

**Comment by furszy** [comment] 2019-11-29 18:50
Functionality not available anymore, closing the issue..

**Closed by furszy** 2019-11-29 18:50 UTC
Labels: GUI
