### ISSUE TITLE
Unlock wallet for staking only by default

### ISSUE THREAD

**Issue by lordg2009** [PIVX-Project/PIVX#613] opened 2018-05-13 16:35 UTC
### Describe the issue
While clicking on Tools -> Unlock wallet, 'Unlocking for staking only' is activated by default. While double clicking on the purple lock the right buttom corner 'Unlocking for staking only' is not activated by default.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. double click on the purple lock in the right buttom corner
2. the checkbox for 'Unlocking for staking only' is not checked by default

### Expected behavior
The checkbox for 'Unlocking for staking only' should be activated by default, regardless on wich way you are unlocking your wallet

### What version of PIVX Core are you using?
3.1.0.2 win64

**Comment by Mrs-X** [comment] 2018-05-13 17:51
Hi there,
thanks for reporting.
A while a go there was a discussion about this (see https://github.com/PIVX-Project/PIVX/pull/521) and I wanted to change it the way you proposed above, but the final decision was to have it NOT checked here.

Depending on the general usage that might be better or worse (e.g. for me it's better to have it unchecked), but you can't make it right for everyone unfortunately.

Maybe we could persist the state somewhere in the future, we'll see.

**Comment by lordg2009** [comment] 2018-05-13 18:26
You can handle it any way I want, but it should be consistent, right?

**Comment by PIVXStrontium** [comment] 2018-05-14 06:47
I'm just getting around to submitting issues from people now lordg2009. I'm glad you've kept to this though. Thank you :).

Mrs-X I'm glad it's on your radar. Not everyone using the wallet is a tech-head, so little inconsistencies like this might be intimidating to users. Thanks for the feedback on this!

**Comment by Mrs-X** [comment] 2018-05-31 12:55
Since the (for this user) expected behavior should be _"The checkbox for 'Unlocking for staking only' should be activated by default, regardless on which way you are unlocking your wallet"_ , and we changed exactly this (people wanted the checkbox status depend on what they want to do) we can close this, there always will be people who want the opposite of what we change, and we can't change it with every release.

BTW, I already thought about a bunch of checkboxes which control the default status of other checkboxes, but figured it would be only a matter of days until someone would want to have the default status for the checkboxes which control the default statuses of the original checkboxes changed.

**Closed by Mrs-X** 2018-05-31 12:55 UTC

**Comment by Rock-N-Troll** [comment] 2018-05-31 15:11
I know this is closed, but I don't see why there couldn't be a setting in the options menu that would satisfy both camps. Ignoring the default case, there could be a setting set by the user in the options menu for how to handle all wallet unlocks moving forward.
