### ISSUE TITLE
[Bug] params don't get copied nor properly placed on macOS 11.3.X

### ISSUE THREAD

**Issue by kyeno** [PIVX-Project/PIVX#2387] opened 2021-05-13 21:52 UTC
**NOTE:** This issue was experienced by one of our community members from #support on two separate machines running macOS 11.3. I wasn't able to reproduce it since I am running an older version of macOS.

## After installing PIVX Core wallet from the DMG archive on macOS 11.3.X, the Sapling Params files do not get copied where they should.

Additionally, when trying to run the PIVX Core, it just crashes with an unspecified error via GUI, and with "Segmentation fault" on CLI. The only hint it leaves is the last line in `debug.log` just before crash, which states it tries to look for Sapling Params.

## The issue was resolved by manually creating `~/Library/Application Support/PIVXParams` directory and copying over the `./usr/share/*` files there from the `.tar.gz` archive.

My assumption is the 11.3 branch of macOS changed some filesystem libraries, APIs or hooks and thus making PIVX Core incompatible.

**Comment by Fuzzbawls** [comment] 2022-05-17 17:36
late reply, but following up on this:

the sapling params for mac `.dmg` versions are self-contained within the app itself, and are not copied to `~/Library/Application Support/PIVXParams`. instead, the wallet looks for the param files within the app bundle:
```cpp
        // macOS fallback path for params located within the app bundle
        // This is a somewhat convoluted series of CoreFoundation calls
        // that will result in the full path to the app bundle's "Resources"
        // directory, which will contain the sapling params.
        LogPrintf("Attempting to find params in app bundle...\n");
        CFBundleRef mainBundle = CFBundleGetMainBundle();
        CFURLRef bundleURL = CFBundleCopyBundleURL(mainBundle);

        CFStringRef strBundlePath = CFURLCopyFileSystemPath(bundleURL, kCFURLPOSIXPathStyle);
        const char* pathBundle = CFStringGetCStringPtr(strBundlePath, CFStringGetSystemEncoding());

        fs::path bundle_path = fs::path(pathBundle);
        LogPrintf("App bundle Resources path: %s\n", bundle_path);
        sapling_spend = bundle_path / "Contents/Resources/sapling-spend.params";
        sapling_output = bundle_path / "Contents/Resources/sapling-output.params";

        // Release the CF objects
        CFRelease(strBundlePath);
        CFRelease(bundleURL);
        CFRelease(mainBundle);
```

tested working as intended on macOS 11.6.4 with PIVX Core v5.4.0.

now closing the issue. if this kind of problem comes up again, open a new issue.

**Closed by Fuzzbawls** 2022-05-17 17:36 UTC
