### ISSUE TITLE
pivx-qt: malloc.c:2406: sysmalloc: Assertion ... ... failed

### ISSUE THREAD

**Issue by HydraGene** [PIVX-Project/PIVX#223] opened 2017-07-22 13:27 UTC
### Describe the issue
PIVX-QT suddenly stops with the following error:
```
myusername@myhost:~$ /opt/pivx/bin/pivx-qt 
pivx-qt: malloc.c:2406: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted
```

### Can you reliably reproduce the issue?
All that really happens is:
1. run command /opt/pivx/pivx-qt from command line
2. pivx-qt randomly crashes with the error above

### Expected behavior
It should run continuously. 

### Actual behavior
It crashes.

### What version of PIVX Core are you using?
I run the official binary build of PIVX.
Version: pivx-2.2.1-x86_64-linux-gnu.tar.gz

### Machine specs:
PIVX is running on a MiniPC, which I use exclusively for the purpose of running cryptocurrencies.
- OS: Debian Stretch
- CPU: Intel i5-5200U
- RAM: 2x 8GB DDR3L - 1600 SSODIMM
- Disk size: 87,8 GB
** /home partition on which the PIVX data is stored
- Disk size: 20,0 GB
** / root partition from which PIVX is running
- Disk Type (HD/SDD): SSD

### Any extra information that might be useful in the debugging process.
Only the last hour before the crash. The complete debug.log file has 409.383 lines which I can't paste all at once...
https://pastebin.com/kYZ5QVpt

**Comment by Fuzzbawls** [comment] 2017-07-23 04:07
Thanks for the report. This is actually a duplicate of #185, which has already been resolved in the master branch and is slated for the next release.

**Closed by Fuzzbawls** 2017-07-23 04:07 UTC
