### ISSUE TITLE
Transaction Time Wrong id Wallet Unsynched. 

### ISSUE THREAD

**Issue by TheDoktar** [PIVX-Project/PIVX#631] opened 2018-06-08 11:34 UTC
### Describe the issue
I am using PIVX core v3.1.0.2 (64-bit). 
I opened the wallet which was several days out of sync and as I was in a hurry I sent a transaction without waiting for sync. This should be fine as the coins are old coins.

The transaction went through Ok but has a bogus date on it. The date shown is 09/04/2018 19.10  while it was actually sent at 08/06/2018 10:13:04 according to a blockchain viewer. This is not even the date of the latest block at the moment I sent it, as I was only about 4 days behind.  The transaction is wrongly positioned in the transaction history and the date is also wrong on the show transaction details window.  The issue is not corrected by stopping and re-starting the client. 

### Can you reliably reproduce the issue?
I think so. 
#### If so, please list the steps to reproduce below:
1. Open an un-synched wallet that is a few days behind. 
2. While it is still synching send a transaction. 
3. Look at the date on the transaction on the transactions screen. 

### Expected behavior
The date should show the current date in the local time zone. 

### Actual behavior
The date is wrong. It seems to be wrong (in the past by)  by about (1 month -1 day -10 hours)  

### What version of PIVX Core are you using?
v3.1.0.2 (64-bit)
Official binary. 

### Machine specs:
- OS: Ubuntu 16.04
- CPU: 
- RAM: 15G. 
- Disk size: 10Tb 
- Disk Type HD. 

### Any extra information that might be useful in the debugging process.
This is the contents of the log file at the time of the transaction: 
  2018-06-08 10:12:07 UpdateTip: new best=ec20ff2ea1961173fbe7fd5420894293601dc124503a57d4b801dcfaa3283fd2  height=1191853  log2_work=69.093597  tx=2635496  date=2018-06-04 08:15:49 progress=0.987338  cache=4928
  2018-06-08 10:12:07 ProcessNewBlock : ACCEPTED Block 1191853 in 301 milliseconds with size=21909
  2018-06-08 10:12:07 CommitTransaction:
CTransaction(hash=04d321a9df, ver=1, vin.size=2, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(b86022e937568a6956385b7a070e1dfb85c8ceaa8270a7faee7a8fadb9648108, 1), scriptSig=3044022042e31d2591513537)
    CTxIn(COutPoint(c5a4b255a49fdc2f9b2febf4aac2d5632dde00fe48e06d90e23bb2eca4497c7d, 1), scriptSig=3045022100e8c4f4858ea18f)
    CTxOut(nValue=3911.50000000, scriptPubKey=OP_DUP OP_HASH160 894d2debfe85)
    CTxOut(nValue=524.77173563, scriptPubKey=OP_DUP OP_HASH160 7d4436ba1eaa)
  2018-06-08 10:12:07 keypool keep 271
  2018-06-08 10:12:07 AddToWallet 04d321a9dfb378d9bc90a2985df8eeb4726cef144053dc80b279ce03db40bcb0  new
  2018-06-08 10:12:07 AddToWallet 04d321a9dfb378d9bc90a2985df8eeb4726cef144053dc80b279ce03db40bcb0
  2018-06-08 10:12:07 Relaying wtx 04d321a9dfb378d9bc90a2985df8eeb4726cef144053dc80b279ce03db40bcb0
  2018-06-08 10:12:07 ProcessNewBlock : block contains 4 zPIV mints and 7 zPIV spends
  2018-06-08 10:12:07 UpdateTip: new best=d123b824cc283bfde3af7b32d6459c20ad72d8cac0562284ebe319d778cc4789  height=1191854  log2_work=69.093598  tx=2635500  date=2018-06-04 08:18:02 progress=0.987343  cache=4934
  2018-06-08 10:12:07 ProcessNewBlock : ACCEPTED Block 1191854 in 527 milliseconds with size=146966
  2018-06-08 10:12:07 ProcessNewBlock : block contains 1 zPIV mints and 0 zPIV spends
  2018-06-08 10:12:07 UpdateTip: new best=5e53ec65e94779970ba43ee1bc6d43d85b38de9b259e561fb4e4d190797ab2fd  height=1191855  log2_work=69.093599  tx=2635503  date=2018-06-04 08:18:54 progress=0.987345  cache=4938
  2018-06-08 10:12:07 ProcessNewBlock : ACCEPTED Block 1191855 in 83 milliseconds with size=796

**Comment by Warrows** [comment] 2018-06-08 11:39
Thanks for your report.
This looks like a duplicate of #510 which I'm currently investigating. In which case it's only a display issue in your wallet without consequence for the security of your funds.
I'd like to know if you have been staking with this wallet and happened to have an orphaned block on 09/04/2018 19.10?

**Comment by TheDoktar** [comment] 2018-06-08 12:28
The answer is yes I do have such an orphaned block at that time. actually 2 in that minute which is unusual. They display either side of the wrongly dated transaction. 

The transaction did go through and was confirmed, so yes U agree its only a display issue. 

I agree it looks like a dupe of #510.

**Closed** 2018-10-13 22:47 UTC
Labels: duplicate
