### ISSUE TITLE
-disablewallet causes Segmentation fault

### ISSUE THREAD

**Issue by knaperek** [PIVX-Project/PIVX#807] opened 2019-02-04 12:58 UTC
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

#### If so, please list the steps to reproduce below:
1. Yes, 100% reproducible:
2. Just run `pivxd -disablewallet`
3. It doesn't even help if I add `staking=0` as well. Still segfaults.

### Expected behavior
PIVXD should just run as a full node, without wallet funcionality.

### Actual behavior
PIVXD crashes with no useful debug. The last line in debug.log is:
```
CObfuscationPool::CheckTimeout() -- Session timed out (30s) -- resetting
```

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.
Official binary run on Ubuntu 18.04
```
$ pivxd --version
Pivx Core Daemon version v3.1.1
```

### Machine specs:
- OS: Ubuntu 18.04
- CPU: AMD Opteron (12 cores)
- RAM: 64 GiB
- Disk size: 2 TB
- Disk Type (HD/SDD): HD

**Comment by cevap** [comment] 2019-02-10 20:33
could not reproduce your issue with current master, here are some screenshots of QT, I would need to wait until the chain syncs to test it which I cant do today, but it looks in QT as if wallet functions are disabled, tried `gebalance` and `getmininginfo` (_see scrennshots below_)

## How to reproduce
compile from pivx master or you can test same version which I used for this test with:
```bash
sudo snap install --edge pivx
pivx.qt --disablewallet
```
Version: `PIVX Core Version v3.1.99.0-3679dcd-dirty (64-Bit)` https://github.com/cevap/PIVX/commit/3679dcd0bc68d6f1bc27360fa7c6d625c833835d

_Those are snap builds from https://github.com/cevap/pivx and will be moved to pivx if PR #782 gets merged._

## Machine specs:
AMD® Ryzen 5 2600 six-core processor × 12

### OS
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

## Scrennshots
- starting normal QT
  ![grafik](https://user-images.githubusercontent.com/24996551/52538945-12ba4200-2d79-11e9-80cc-b42872cd82cb.png)
- starting QT with `--disablewallet`
  ![grafik](https://user-images.githubusercontent.com/24996551/52538967-50b76600-2d79-11e9-9177-5a71a1b81fe9.png)
  ![grafik](https://user-images.githubusercontent.com/24996551/52539077-46e23280-2d7a-11e9-9e79-a0d6cde67074.png)

**Comment by knaperek** [comment] 2019-02-11 09:18
* I only tested it with `pivxd` (not the QT version), although I don't suppose there will be a difference.
* However I noticed that it crashes at the chain tip - so you probably can't reproduce it because it's not synced yet. Wait until it fully syncs and it should crash...

**Comment by cevap** [comment] 2019-02-12 23:15
yes, when synced, I can fully reproduce and confirm this bug

**Comment by cevap** [comment] 2019-02-12 23:33
@knaperek 
I guess you do not require BitcoinMiner when running with `disablewallet`

If you markout [here](https://github.com/PIVX-Project/PIVX/blob/ed0dd2a20a87e9de56e9ff33387a8e68043fe840/src/net.cpp#L1566) `BitcoinMiner(pwallet, true);`and recompile with
```c++
// ppcoin: stake minter thread
void static ThreadStakeMinter()
{
    boost::this_thread::interruption_point();
    LogPrintf("ThreadStakeMinter started\n");
    CWallet* pwallet = pwalletMain;
    try {
        //BitcoinMiner(pwallet, true);
        boost::this_thread::interruption_point();
    } catch (std::exception& e) {
        LogPrintf("ThreadStakeMinter() exception \n");
    } catch (...) {
        LogPrintf("ThreadStakeMinter() error \n");
    }
    LogPrintf("ThreadStakeMinter exiting,\n");
}
```

your wallet will launch, I tested it on another fork so I will not upload screenshot, but here is of terminal.

Here is a workaround patch if you want to try it.
```
From 14232f176400e65d489a33fb3cf392412603a279 Mon Sep 17 00:00:00 2001
From: observerdev <dev@obsr.org>
Date: Wed, 13 Feb 2019 00:28:59 +0100
Subject: [PATCH] Workaround for disablewallet until fixed

---
 src/net.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/net.cpp b/src/net.cpp
index b515ebb65..4682d1f24 100644
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -1563,7 +1563,7 @@ void static ThreadStakeMinter()
     LogPrintf("ThreadStakeMinter started\n");
     CWallet* pwallet = pwalletMain;
     try {
-        BitcoinMiner(pwallet, true);
+        //BitcoinMiner(pwallet, true);
         boost::this_thread::interruption_point();
     } catch (std::exception& e) {
         LogPrintf("ThreadStakeMinter() exception \n");
-- 
2.17.1

```
 you might also remove pwallet var at all if this warning disturbs:
`net.cpp:1565:14: warning: unused variable ‘pwallet’ [-Wunused-variable]`

**Comment by cevap** [comment] 2019-02-12 23:49
I did not let it run to see if it crashes with only marking that line out, but I would also assume that also `boost::this_thread::interruption_point();` should be marked out, otherwise it will at some point catch some exception and  quit.

if you test and it crashes after some time running, you can try marking boost part also out
```
        //BitcoinMiner(pwallet, true);
        //boost::this_thread::interruption_point();
```

this shouid be easy to fix.

**Comment by cevap** [comment] 2019-02-13 00:10
boost as error handling marked out, now it does not segfault receiving next block, will wait an hour or two to see if it segfaults, compiled with:
```c++
//    boost::this_thread::interruption_point();
    LogPrintf("ThreadStakeMinter started\n");
    CWallet* pwallet = pwalletMain;
    /*
    try {
        BitcoinMiner(pwallet, true);
        boost::this_thread::interruption_point();
    } catch (std::exception& e) {
        LogPrintf("ThreadStakeMinter() exception \n");
    } catch (...) {
        LogPrintf("ThreadStakeMinter() error \n");
    }
    LogPrintf("ThreadStakeMinter exiting,\n");
    */
}
```

**Comment by Fuzzbawls** [comment] 2019-02-24 09:04
See #817 for a fix that is compatible with both wallet enabled and wallet disabled runtime options.

**Comment by Fuzzbawls** [comment] 2019-03-19 11:36
closing now that #817 has been merged

**Closed by Fuzzbawls** 2019-03-19 11:36 UTC
Labels: Bug, Wallet
