### ISSUE TITLE
"Generated but not accepted minted" transactions never clear from Overview Screen

### ISSUE THREAD

**Issue by claydigger** [PIVX-Project/PIVX#116] opened 2017-04-15 22:46 UTC
I have received a number of "Generated but no accepted minted" transactions and they are crowding the Overview Screen of the pivx-qt ver 2.1.7.0 wallet running on Raspberry Pi 3b x-windows GUI.  When I receive a new transaction, it falls to the very bottom of the Overview Screen because the "generated but not accepted minted" transaction never clear from the screen and are never pushed out of view. Please fix this bug so that bad blocks eventually get pushed out of view.

please send any Bug Bounty pivx to address: D5Uf9bMNCrhLH9uquy8mBr5A9QnqudZQKQ
![image](https://cloud.githubusercontent.com/assets/11659040/25067264/da3664c4-220b-11e7-8916-33727849d760.png)

**Comment by Fuzzbawls** [comment] 2017-04-15 22:48
Duplicate of #111, fixed in #112

**Closed by Fuzzbawls** 2017-04-15 22:48 UTC
