### ISSUE TITLE
Payment to self showing 3 times

### ISSUE THREAD

**Issue by borris345** [PIVX-Project/PIVX#1514] opened 2020-04-10 14:41 UTC
Same transaction showing 3 times. It is the exact same transaction. Latest master pull.

![15865296308403545251592543994844](https://user-images.githubusercontent.com/27918951/78999051-c1a30b00-7b41-11ea-88bf-c5913b488d8e.jpg)

**Comment by random-zebra** [comment] 2020-04-10 14:45
Duplicate of  #1480

**Closed by random-zebra** 2020-04-10 14:45 UTC
