### ISSUE TITLE
v3.2.0 Crashing – macOS & Windows

### ISSUE THREAD

**Issue by Nakamoto-san** [PIVX-Project/PIVX#864] opened 2019-04-12 18:30 UTC
**macOS 10.14.4** – 1. Issue(s) with mounted volume containing pre-compiled binary. 2. Experiencing constant crashing when starting/loading wallet. If no crash during startup, will eventually crash once opened. 3. Additionally, UI contains odd 'pink' around borders and/or frames of the application. Have successfully replicated theses issue across multiple machines with similar OS versions.

**Windows 10** – Experience crash while syncing wallet – not immediately, but eventually. Have successfully replicated this issue across multiple machines as well.

**Comment by Warrows** [comment] 2019-04-12 23:16
Please open one issue per situation and check if there is no open issue for the problems you report.

What you describe here seems to be duplicate of #854 and #859 so I'll close this issue. If you happen to have a crash under a different situation please open a new issue with more information to help us debug.

**Closed by Warrows** 2019-04-12 23:16 UTC
