### ISSUE TITLE
Starting Masternode from GUI does not work

### ISSUE THREAD

**Issue by Newar417** [PIVX-Project/PIVX#482] opened 2018-01-08 10:48 UTC
Tried to start the MN from the GUI. Received a message about invalid IP. 

Started from Debug console, no problem.

### Can you reliably reproduce the issue?
Yes, ever single time when trying to start the MN.

### Expected behavior
The MN should start from GUI.

### Actual behavior
It does not and throws an incorrect error message,

### What version of PIVX Core are you using?
Latest binary

### Machine specs:
Debian stable (remote and local)

**Comment by Sieres** [comment] 2018-01-08 11:17
Come chat to us on discord https://discord.gg/uAZUhF4

**Comment by rejectedpromise** [comment] 2018-01-11 23:16
@Sieres has this been resolved through on discord?

**Comment by Mrs-X** [comment] 2018-01-13 23:06
This is a bug and on my todo-list for ages.
I'll take care of this.

**Comment by Sieres** [comment] 2018-01-14 04:05
I spoke to him and provided him to the setup guide he should be using, he mentioned he will use that guide and complete the setup. I haven't heard from him since, so I'm going to assume his was able to complete setup of the masternode.

**Comment by Newar417** [comment] 2018-01-14 09:55
Well, I did not have to start the wallet again, since I started through the console prior to submitting this issue.

If anything, the documentation could be improved. From the main PIVX site, there are eventually two links to setup a MN. Sieres kindly pointed me towards another one in the knowledge base. Those three guides do vary slightly on some points.

**Comment by Fuzzbawls** [comment] 2018-02-09 12:28
duplicate of #373, going to close this one.

**Closed by Fuzzbawls** 2018-02-09 12:28 UTC
Labels: Bug, GUI
