### ISSUE TITLE
wallet 2.2  x86_64 on linux won't start

### ISSUE THREAD

**Issue by BassHunger** [PIVX-Project/PIVX#148] opened 2017-04-25 08:21 UTC
### Describe the issue
I am using a LinuxMint 18.1 64bit Cinnamon PC, AMD 4xcore; till know i've used the 2.1.3 version in the last months with uptimes of 10-30days without any issue;   
now I downloaded Pivx 2.2 wallet + resynced wallet from scratch (as blockchain was corrupted after update)
after that Sync- all was fine (total Balance correct) - restarted PC and after that, pivx wallet won't start; with several Linux kernels 4.8 - Version 49; Version 46...

Error message i always get is:
pivx-qt: main.cpp:2300: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
Aborted

#### If so, please list the steps to reproduce below:
1.yes, see above, with several kernels
2.
3.

### Expected behavior
wallet should start and stake as before

### Actual behavior
wallet abort

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
v2.2.0  linux-x86_64  - downloaded from github

### Machine specs:
- OS: LinuxMint 18.1  64 bit - Cinnamon
- CPU: 4core AMD
- RAM: 5 GB
- Disk size: 1 TB
- Disk Type (HD/SDD): HDD

### Any extra information that might be useful in the debugging process.
debug.log - pastebin link:
https://pastebin.com/f5CT8pj1

**Comment by presstab** [comment] 2017-04-25 15:23
Duplicate of https://github.com/PIVX-Project/PIVX/issues/106

We believe, but are not sure we have a solution please test https://github.com/PIVX-Project/PIVX/pull/146

If you cannot build from source, here is a binary that we had compiled https://www.dropbox.com/s/g3zbsynw3zb6f35/pivx-2.2.99-x86_64-linux-gnu.tar.gz

**Closed by presstab** 2017-04-25 15:23 UTC
