### ISSUE TITLE
Wallet displaying wrong date for stake

### ISSUE THREAD

**Issue by dikel** [PIVX-Project/PIVX#785] opened 2018-12-25 10:00 UTC
### Describe the issue
Wallet is showing wrong date for my last stake.

### Can you reliably reproduce the issue?
No.

### Expected behavior
The stake should have today's date

### Actual behavior
I staked on 12/15/18 but it was orphan. Then I staked on 12/17/18. Today (12/25/18) I staked again but it shows the date of the orphan stake (12/15/18) and even the same hour and minutes.

### Screenshots.
![screenshot_2018-12-25_11-54-26](https://user-images.githubusercontent.com/9680010/50419922-1ed75800-083c-11e9-8820-818305690cd4.png)

As you can see from the screenshot, the wallet shows the stake is from more than a week ago but it has only 140 confirmations.

### What version of PIVX Core are you using?
The official 3.1.1 binary.

### Machine specs:
- OS: Pop!_OS
- CPU: Intel Pentium
- RAM: 4GB
- Disk size: 500GB
- Disk Type (HD/SDD): HD

**Comment by Warrows** [comment] 2018-12-25 12:49
Duplicate of #510

**Closed** 2019-07-28 08:05 UTC
