### ISSUE TITLE
EXCEPTION: St9bad_alloc        on startup, after crash due low disk space

### ISSUE THREAD

**Issue by baryluk** [PIVX-Project/PIVX#634] opened 2018-06-11 21:54 UTC
```
~/Linux/pivx/pivx-3.1.0/bin$ LC_ALL=C ./pivx-qt 
bash: uwaga: setlocale: LC_ALL: nie można zmienić lokalizacji (C./pivx-qt): Zły argument


************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
pivx in Runaway exception       

pivx-qt: /home/ubuntu/build/pivx/depends/x86_64-linux-gnu/share/../include/boost/thread/pthread/condition_variable_fwd.hpp:116: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
Przerwane
```

**Comment by baryluk** [comment] 2018-06-11 22:04
And not it is unusable. I now have 16GB of free space, but `pivx-qt` crashes every time just on startup when unlocking wallet.

**Comment by baryluk** [comment] 2018-06-11 22:05
```
2018-06-11 21:42:19 PIVX version v3.1.0.2 (2018-05-02 14:25:18 -0700)
2018-06-11 21:42:19 Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
2018-06-11 21:42:19 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2018-06-11 21:42:19 Default data directory /home/baryluk/.pivx
2018-06-11 21:42:19 Using data directory /home/baryluk/.pivx
2018-06-11 21:42:19 Using config file /home/baryluk/.pivx/pivx.conf
2018-06-11 21:42:19 Using at most 125 connections (65536 file descriptors available)
2018-06-11 21:42:19 Using 12 threads for script verification
2018-06-11 21:42:19 scheduler thread start
2018-06-11 21:42:19 Creating backup of "/home/baryluk/.pivx/wallet.dat" -> "/home/baryluk/.pivx/backups/wallet.dat.2018-06-11-21-42"
2018-06-11 21:42:19 Using wallet wallet.dat
2018-06-11 21:42:19 init message: Verifying wallet...
2018-06-11 21:42:19 CDBEnv::Open: LogDir=/home/baryluk/.pivx/database ErrorFile=/home/baryluk/.pivx/db.log
2018-06-11 21:42:19 Bound to [::]:51472
2018-06-11 21:42:19 Bound to 0.0.0.0:51472
2018-06-11 21:42:19 init message: Loading block index...
2018-06-11 21:42:19 Opening LevelDB in /home/baryluk/.pivx/zerocoin
2018-06-11 21:42:19 Opened LevelDB successfully
2018-06-11 21:42:19 Opening LevelDB in /home/baryluk/.pivx/sporks
2018-06-11 21:42:19 Opened LevelDB successfully
2018-06-11 21:42:19 Opening LevelDB in /home/baryluk/.pivx/blocks/index
2018-06-11 21:42:19 Opened LevelDB successfully
2018-06-11 21:42:19 Opening LevelDB in /home/baryluk/.pivx/chainstate
2018-06-11 21:42:19 Opened LevelDB successfully
2018-06-11 21:42:19 init message: Loading sporks...
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_2_SWIFTTX found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_3_SWIFTTX_BLOCK_FILTERING found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_5_MAX_VALUE found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_7_MASTERNODE_SCANNING found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_8_MASTERNODE_PAYMENT_ENFORCEMENT found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_9_MASTERNODE_BUDGET_ENFORCEMENT found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_10_MASTERNODE_PAY_UPDATED_NODES found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_13_ENABLE_SUPERBLOCKS found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_14_NEW_PROTOCOL_ENFORCEMENT found in database
2018-06-11 21:42:19 LoadSporksFromDB : no previous value for SPORK_15_NEW_PROTOCOL_ENFORCEMENT_2 found in database
2018-06-11 21:42:19 LoadSporksFromDB : loaded spork SPORK_16_ZEROCOIN_MAINTENANCE_MODE with value 1555806990 : Sun Apr 21 02:36:30 2019
2018-06-11 21:42:19 init message: Loading block index...
2018-06-11 21:42:52 LoadBlockIndexDB: last block file = 20
2018-06-11 21:42:52 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=1, size=146195, heights=1199919...1199919, time=2018-06-09...2018-06-09)
2018-06-11 21:42:52 Checking all blk files are present...
2018-06-11 21:42:53 LoadBlockIndexDB: Last shutdown was prepared: false
2018-06-11 21:42:53 LoadBlockIndexDB(): transaction index enabled
2018-06-11 21:42:53 LoadBlockIndexDB(): hashBestChain=9b6b1891a04ef37385b4c3af88c02e9c197ede442a041891f82aa74fe5ede524 height=1199919 date=2018-06-09 23:24:03 progress=0.994169
2018-06-11 21:42:53 init message: Verifying blocks...
2018-06-11 21:42:53 Verifying last 100 blocks at level 4
2018-06-11 21:43:09 No coin database inconsistencies in last 101 blocks (279 transactions)
2018-06-11 21:43:09  block index           49496ms
2018-06-11 21:43:09 init message: Loading wallet...
2018-06-11 21:43:09 nFileVersion = 3010002
2018-06-11 21:43:09 Keys: 1001 plaintext, 0 encrypted, 1001 w/ metadata, 1001 total
2018-06-11 21:43:09  wallet                   38ms
2018-06-11 21:43:09 init message: Syncing zPIV wallet...
2018-06-11 21:43:09 GenerateMintPool : n=1 nStop=20
2018-06-11 21:43:09 SyncWithChain: Mintpool size=20
2018-06-11 21:43:09 init message: Loading masternode cache...
2018-06-11 21:43:09 ERROR: Read : Failed to open file /home/baryluk/.pivx/mncache.dat
2018-06-11 21:43:09 Missing masternode cache file - mncache.dat, will try to recreate
2018-06-11 21:43:09 init message: Loading budget cache...
2018-06-11 21:43:09 ERROR: Read : Failed to open file /home/baryluk/.pivx/budget.dat
2018-06-11 21:43:09 Missing budget cache - budget.dat, will try to recreate
2018-06-11 21:43:09 init message: Loading masternode payment cache...
2018-06-11 21:43:09 ERROR: Read : Failed to open file /home/baryluk/.pivx/mnpayments.dat
2018-06-11 21:43:09 Missing masternode payment cache - mnpayments.dat, will try to recreate
2018-06-11 21:43:09 Locking Masternodes:
2018-06-11 21:43:09 fLiteMode 0
2018-06-11 21:43:09 nSwiftTXDepth 5
2018-06-11 21:43:09 Anonymize PIVX Amount 2
2018-06-11 21:43:09 Budget Mode auto
2018-06-11 21:43:09 mapBlockIndex.size() = 1199920
2018-06-11 21:43:09 chainActive.Height() = 1199919
2018-06-11 21:43:09 setKeyPool.size() = 1000
2018-06-11 21:43:09 mapWallet.size() = 0
2018-06-11 21:43:09 mapAddressBook.size() = 1
2018-06-11 21:43:09 init message: Loading addresses...
2018-06-11 21:43:09 

************************
EXCEPTION: St9bad_alloc       
std::bad_alloc       
pivx in Runaway exception       

2018-06-11 21:43:09 torcontrol thread start
2018-06-11 21:43:16 CDBEnv::EnvShutdown : Error 22 shutting down database environment: Invalid argument
```

**Comment by Warrows** [comment] 2018-06-12 06:51
You should try method 4 from this page: https://pivx.freshdesk.com/support/solutions/articles/30000029354-how-to-resync-your-blockchain-cache

**Comment by Warrows** [comment] 2018-06-12 18:34
Alright, could you then provide instructions to reliably reproduce the bug?

**Comment by baryluk** [comment] 2018-06-12 19:24
I provided debug log from when it crashed. It is in a third post.

**Comment by Fuzzbawls** [comment] 2019-01-18 10:22
Sorry for the late reply here:

The issue is that your on-disk database files are corrupted due to insufficient available disk space. Freeing up space post-corruption will not in itself fix the corrupted state of these files. the `db.log` file should have contained information about this, but may not have if the available disk space was less than what was required to write to that log.

With this type of data corruption, the only remedy is to remove the corrupted files and re-create them by way of syncing from the network. Self-recovery is not possible in this situation because the corruption can occur at any point within any (or all) active file(s).

**Comment by Fuzzbawls** [comment] 2019-03-29 00:14
Closing, no further commentary

**Closed by Fuzzbawls** 2019-03-29 00:14 UTC
