### ISSUE TITLE
[Bug] Bypassing 5 confirmations requirement for spending shield notes

### ISSUE THREAD

**Issue by ambassador000** [PIVX-Project/PIVX#2651] opened 2021-11-27 03:39 UTC
For example, if you have 10 shielded PIVs with 1 confirmations on blockchain, if you want to spend this UTXO and send 8 shielded PIVs to your transparent address, the following error will appear:
![confirmations5](https://user-images.githubusercontent.com/57232689/143666633-15a61f98-8836-4e2d-ac81-95934d10ad91.jpg)

However, it is possible to bypass this error and spend the shielded note(s) with 1 confirmation only.

Steps to reproduce:

1. Send transparent coins to any of your shield address.
2. Wait for 1 confirmation on blockchain.
3. Open `SEND` tab -> choose `Shielded` send option -> paste your Transparent address in the `Recipient address` field -> open Coin Control -> click `Select All` -> copy the Amount -> paste the amount in the `Amount` field -> check `Subtract fee from amount` option -> click `Send` button -> **Transaction can be sent without an error** (Shielded UTXO(s) can be spent with 1 confirmation only).

Reproducible with multiple shielded UTXOs as well.

**Comment by furszy** [comment] 2021-11-27 12:22
The 5 blocks minimum depth is just a visual warning, to prevent the transactions to orphan in case of chain reorgs. In other words, prevent a headache for the user.
When you select the utxo manually, using the coin control features, you are deciding which utxo to spend, thus why you are able to by-pass the minimum recommended depth. Same reason behind why you could spend an unconfirmed transaction output as well and many other "not recommended for non-advanced users" transaction customizations.

**Comment by panleone** [comment] 2023-07-16 07:49
closing since this is not a bug

**Closed by panleone** 2023-07-16 07:49 UTC
