### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by piratoskratos** [PIVX-Project/PIVX#764] opened 2018-11-02 12:11 UTC
On linux, pivx 3.1.1; ram usage is way too much. 

**1.8 gb**... To compare  litecoin takes 500 mb.

Under 1gb it will be more acceptable.

**Comment by Carbon-Zero** [comment] 2019-02-28 20:37
Please provide more information about the environment, how you compiled it, etc.

**Comment by piratoskratos** [comment] 2019-03-01 11:55
Debian, precompiled version pivx-3.1.1-x86_64-linux-gnu.tar.gz. At the moment 1.52gb.

From all thumbs up on this issue, I guess it's not linked from my end but the program itself... Dashd is running on the same machine (0.51 gb used)

**Comment by vereten** [comment] 2019-05-07 18:31
![000](https://user-images.githubusercontent.com/11050858/57323700-85338780-7106-11e9-8091-cdd98432824a.png)
![0001](https://user-images.githubusercontent.com/11050858/57323844-d774a880-7106-11e9-9571-884cdd2e5819.png)

I have same problem with Debian/testing also with Ubuntu 18.04.2 LTS (Bionic Beaver) 64-bit.
compiled from source with no special options, just db4 used.

**Comment by niex2** [comment] 2019-05-09 16:33
I think my problem is related to this, but I'm not sure.
When I try to sync the blockchain (I tried with bootstrap file as well) the process reaches a point where I get the error "Segmentation Fault", after I restart, I will get the error:

`pivx-qt: main.cpp:2757: void RecalculateZPIVMinted(): Assertion `ReadBlockFromDisk(block, pindex)' failed.
Aborted
`

The memory usage is really high (program will quite at 4 GB)
This is a VM, based on Debian-9.

**Comment by vereten** [comment] 2019-05-09 16:58
> I think my problem is related to this, but I'm not sure.
> When I try to sync the blockchain (I tried with bootstrap file as well) the process reaches a point where I get the error "Segmentation Fault", after I restart, I will get the error:
> 
> `pivx-qt: main.cpp:2757: void RecalculateZPIVMinted(): Assertion ReadBlockFromDisk(block, pindex)' failed. Aborted `
> 
> The memory usage is really high (program will quite at 4 GB)
> This is a VM, based on Debian-9.

Seems your issue is another issue. I was experiencing same issue when i was syncing blockchain from scratch. My workaround for your issue was: to not use pivx-qt, instead to use pivxd and wait for full sync. pivxd will crash same as pivx-qt but pivxd is able to recover from that error after restart. Than please make snapshot of whole .pivx folder for functional backup. than you can use pivx-qt.
I was syncing with this script to autorestart pivxd after any crash. Before using script please update <pivxd_path> with your latest pivxd version 3.2.2 path. Good luck.
`#!/bin/bash
while true
do
cd <pivxd_path> && ./pivxd -printtoconsole -enablezeromint=0 -staking=0 
sleep 3
`
push this to file.sh than start by sh file.sh

**Comment by niex2** [comment] 2019-05-10 08:27
it's always failing at block 892000

**Comment by mrcarlanthony** [comment] 2019-05-22 15:10
A developer is starting a pre-proposal to fix this issue, funded by PIVX DAO.

please view information on the forum : https://forum.pivx.org/index.php?threads/fix-of-ram-issue-764-pre-proposal-discussion-dev-attention-needed-if-possible.221/

thanks

**Comment by akshaynexus** [comment] 2019-05-22 15:27
as per error report from  @niex2 assert(ReadBlockFromDisk(block, pindex)); is failing, the causes I see possible causing this is the recalculate functions from that error report.

**Comment by presstab** [comment] 2019-05-23 21:36
With a couple hours of tinkering, I was able to reduce the memory down to 1gb. There are still other optimizations that could cut off another 50-100mb.

**Comment by vereten** [comment] 2019-05-24 12:56
great to hear, way to go :)

**Comment by vgtom** [comment] 2019-05-25 17:43
@presstab...well naturally you have a head start over others...but you have still reduced memory very little...What i propose is a total solution. Professional code. And Professional Software.

**Comment by presstab** [comment] 2019-06-02 19:23
Almost 1/2 reduction in memory use is small? Ok.

**Comment by gaojian1139** [comment] 2019-06-23 08:29
i’m using ARM64 and it show around 3.5Gb is required.  2GB RAM with 1.8G swap.....

**Comment by random-zebra** [comment] 2020-04-12 14:58
Closing with #1502 for now.
Probably there will be more improvements in the coming future too.

**Closed by random-zebra** 2020-04-12 14:58 UTC
