### ISSUE TITLE
PIVX Wallet core dump

### ISSUE THREAD

**Issue by mbay1971** [PIVX-Project/PIVX#205] opened 2017-06-26 14:01 UTC
### Describe the issue

the wallet-qt version 2-2-1 regularly core dumps with this error:
pivx-qt: malloc.c:2394: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.                                                                                                                                                                                                 
Aborted (core dumped) 

#### If so, please list the steps to reproduce below:
1. start the wallet-qt
2. wait until core dump appears (between minutes and some hours )

### Expected behavior
wallet-qt should stay up and tunning stable

### Actual behavior
wallet-qt core dumps regularly

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of PIVX Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

OS is running as KVM instance !

- CPU: 
4 cores
- RAM:
12 GB
- Disk size
200 GB

- Disk Type (HD/SDD):
HDD (KVM VMDK QCOW2)

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by Fuzzbawls** [comment] 2017-07-02 01:40
somewhat a duplicate of #185 

PR #206 does address the issue (while at the same time cleaning up the UI) ;)

**Comment by Fuzzbawls** [comment] 2017-07-08 22:05
fixed in #206

**Closed by Fuzzbawls** 2017-07-08 22:05 UTC
Labels: Bug, GUI
