### ISSUE TITLE
Orphaned transaction time mismatch

### ISSUE THREAD

**Issue by DSofter** [PIVX-Project/PIVX#510] opened 2018-01-24 15:16 UTC
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Discord](https://discord.pivx.org).

### Describe the issue

Hello PIVX devs! I'm seeing transaction time mismatch on my desktop wallet.

On the transaction list, the tx happened at 1/19/2018 23:30, as shown in the below screenshot:
![image](https://user-images.githubusercontent.com/1687829/35339419-6ff3169e-00d5-11e8-85d7-0e3bf0f43414.png)

However in the blockchain explorer, the tx happened at 1/20/2018 18:15
![image](https://user-images.githubusercontent.com/1687829/35339463-8e88147e-00d5-11e8-857c-6b4d9e113e56.png)

I don't know if it might be the cause, but I'm only noticing such behavior on orphaned transactions. The transaction I posted above is an orphaned transaction.
![image](https://user-images.githubusercontent.com/1687829/35339797-5b92aa1a-00d6-11e8-9789-28caf1b11475.png)

#### If so, please list the steps to reproduce below:
1. I resynced my wallet and the issue is still there.

### Expected behavior
The time of the transaction should match between the transaction list and the block explorer.

### Actual behavior
The time of the transaction didn't match between the transaction list and the block explorer.

### Screenshots.
Posted above.

### What version of PIVX Core are you using?
3.0.6

**Comment by Warrows** [comment] 2018-01-24 15:43
Duplicate of #204. Not sure if #498 really fixed it or not.

**Comment by DSofter** [comment] 2018-01-24 17:00
Lemme try that! Thanks for the quick response! @Warrows

**Comment by DSofter** [comment] 2018-01-24 17:04
@Warrows Actually, although https://github.com/PIVX-Project/PIVX/pull/498 was merged, do I still need to wait for the new release, or download and compile the latest code before trying `-zapwallettxes`?

**Comment by Warrows** [comment] 2018-01-24 23:47
@DSofter as a first step you can go ahead and zap with your current wallet. If it doesn't work I would be very interested in you trying to zap with binaries compiled from master.

**Comment by DSofter** [comment] 2018-01-25 01:46
@Warrows may i also ask what the `zapwallettxes` command does?

**Comment by Warrows** [comment] 2018-01-25 08:23
It's going to remove all TX from memory and rescan the blockchain to add them all back. It can be a long process of you have a lot of transactions.
Of course I advise you to backup wallet.dat before any of these operations as a simple safety measure.

**Comment by Warrows** [comment] 2018-05-21 19:54
Looks like it's not really fixed after all. A user reported it again a few days ago.
![capture](https://user-images.githubusercontent.com/835098/40326969-7524e5de-5d41-11e8-873c-c2f3e96c7912.PNG)

**Closed** 2019-07-28 00:13 UTC
Labels: Bug, GUI
