### ISSUE TITLE
Pivx wallet crashed on Raspberry Pi 3

### ISSUE THREAD

**Issue by nghiacc** [PIVX-Project/PIVX#132] opened 2017-04-22 03:36 UTC
I installed a fresh Raspbian Jessie on RPi3, and installed the Pivx wallet https://github.com/PIVX-Project/PIVX/releases/download/v2.2.0/pivx-2.2.0-arm-linux-gnueabihf.tar.gz

The wallet ran fine, was able to sync. I replaced my backup wallet, and start staking. There was a green symbol indicating everything was fine. Then I left the wallet running. After few hours, I checked again and didn't see the wallet running anymore.

debug.log
```
2017-04-22 03:44:51 PIVX version v2.2.0 (2017-04-18 19:35:06 -0700)
2017-04-22 03:44:51 Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
2017-04-22 03:44:51 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2017-04-22 03:44:51 Default data directory /home/pi/.pivx
2017-04-22 03:44:51 Using data directory /home/pi/.pivx
2017-04-22 03:44:51 Using config file /home/pi/.pivx/pivx.conf
2017-04-22 03:44:51 Using at most 125 connections (65536 file descriptors available)
2017-04-22 03:44:51 Using 4 threads for script verification
2017-04-22 03:44:51 Using wallet wallet.dat
2017-04-22 03:44:51 init message: Verifying wallet...
2017-04-22 03:44:51 CDBEnv::Open: LogDir=/home/pi/.pivx/database ErrorFile=/home/pi/.pivx/db.log
2017-04-22 03:44:51 Bound to [::]:51472
2017-04-22 03:44:51 Bound to 0.0.0.0:51472
2017-04-22 03:44:51 init message: Loading block index...
2017-04-22 03:44:51 Opening LevelDB in /home/pi/.pivx/blocks/index
2017-04-22 03:44:51 Opened LevelDB successfully
2017-04-22 03:44:51 Opening LevelDB in /home/pi/.pivx/chainstate
2017-04-22 03:44:51 Opened LevelDB successfully
2017-04-22 03:47:45 LoadBlockIndexDB: last block file = 3
2017-04-22 03:47:45 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=27575, size=29155261, heights=582461...610041, time=2017-04-02...2017-04-22)
2017-04-22 03:47:45 Checking all blk files are present...
2017-04-22 03:47:45 LoadBlockIndexDB: Last shutdown was prepared: false
2017-04-22 03:47:45 LoadBlockIndexDB: Inconsistent State Detected mapBlockIndex.size()=610083 blockFileBlocks=610042
2017-04-22 03:47:45 LoadBlockIndexDB: lastIndexPos=29194079 blockFileSize=29155261
2017-04-22 03:47:45 LoadBlockIndexDB: Attempting to re-add last block that was recorded to disk
2017-04-22 03:47:45 LoadBlockIndexDB: Last block properly recorded: #610040 333b0f7684d76535007737725d77ec724b61270f95d2135b3809ad5e42bc68e0
2017-04-22 03:47:46 ConnectBlock: hashPrev=79b646cb62c67b25d213adb44092934561aee299b2aecbf13f2f8ef2e8d56000 view=79fa6d88a44837c2c0e73ffcb6c2caa134cce06f47332865954a0b65c03ed3d6
```

Db.log is empty

**Comment by Fuzzbawls** [comment] 2017-04-22 03:58
You can try running with the -forcestart option: `pivxd -forcestart`
pay attention to any lines that are output to the terminal directly (such as assertion failures or segfaults)

If that doesn't work, then you can try a fresh sync by removing everything in your datadir (`~/.pivx`) except `wallet.dat`, `pivx.conf`, and `masternode.conf`

**Comment by nghiacc** [comment] 2017-04-22 08:50
pi@raspberrypi:~/app/pivx-2.2.0/bin $ ./pivxd
pivxd: main.cpp:2300: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.
Aborted

**Comment by presstab** [comment] 2017-04-23 05:01
Duplicate of https://github.com/PIVX-Project/PIVX/issues/106

**Closed by presstab** 2017-04-23 05:01 UTC
