### ISSUE TITLE
Proposal FeeTX is not valid

### ISSUE THREAD

**Issue by demodun** [PIVX-Project/PIVX#187] opened 2017-05-21 10:04 UTC
This issue tracker is only for technical issues related to PIVX Core.
General PIVX questions and/or support requests and are best directed to the [PIVX Slack](http://pivx.slack.com).

### Describe the issue
Have a look at my forum posts:
https://forum.pivx.org/t/howto-create-a-proposal/959/9

The message "Proposal FeeTX is not valid" appears before 6/6 confirmations.
https://github.com/PIVX-Project/PIVX/blob/master/src/rpcmasternode-budget.cpp#L185
The 50 proposal fee is gone, but no vote appears and whoever may be a new user is confused and believes that their coin are gone.

The solution for the user is to wait a little bit, and resubmit. But this should be prevented, and the system should send a clear message WITHOUT confiscating the coins.
### Can you reliably reproduce the issue?
Yes, try to propose something in the budget before confirmation
#### If so, please list the steps to reproduce below:
1. Open a wallet
2. As soon as possible prepare and submit a proposal
3. The 50 PIV are gone, but the proposal is not submited

### Expected behavior
The submition should be denied if there is no confirmation 6/6
https://github.com/PIVX-Project/PIVX/blob/master/src/rpcmasternode-budget.cpp#L185

### Actual behavior
The submition occurs, the PIV is gone, but no voting hash appears.

### What version of PIVX Core are you using?
2.2.1

### Machine specs:
- OS: Lubuntu
- CPU: Pentium
- RAM: 1.5 Giga

**Comment by Fuzzbawls** [comment] 2017-05-23 20:20
The 50 PIV Collateral is debited during the `prepare` step, and needs 6 confirmations before being accepted by the `submit` step.

This is by design, as proposal submission require a confirmed collateral transaction for submission.

**Comment by PIVX-Project** [comment] 2017-06-13 05:35
I am closing this issues as it works like it should.

**Closed by PIVX-Project** 2017-06-13 05:35 UTC
