### ISSUE TITLE
Subtraction error when funds are recieved.

### ISSUE THREAD

**Issue by alibyte** [PIVX-Project/PIVX#126] opened 2017-04-19 21:11 UTC
Example:
When you have, let's say, 500 PIV available, and recieve 25, it won't show your total as 525. It would show it as 475 total with 25 pending and 450 confirmed. 

Intended result: 500 confirmed, 25 pending, 525 total.

**Comment by presstab** [comment] 2017-04-19 21:14
Duplicate of https://github.com/PIVX-Project/PIVX/issues/118

**Comment by sabhiram** [comment] 2017-04-19 21:14
Duplicate

**Closed by presstab** 2017-04-19 21:14 UTC
