### ISSUE TITLE
[Bug] Request payment with 0.00 PIV

### ISSUE THREAD

**Issue by NoobieDev12** [PIVX-Project/PIVX#1614] opened 2020-05-11 01:19 UTC
Wallet allows creation of Payment Request with empty fields, which results with Payment Request of 0.00 PIV.

![paymentRequest1](https://user-images.githubusercontent.com/57232689/81515810-0b943200-9336-11ea-984e-ae9aaaaa0724.JPG)

![paymentRequest2](https://user-images.githubusercontent.com/57232689/81515812-0df68c00-9336-11ea-9f65-4a491a044ea7.JPG)

**Comment by furszy** [comment] 2020-05-11 20:23
Not a bug, the user could send a 0.00 PIV request with extra notes in the description field. Take this as a QR with extra information.

**Comment by Fuzzbawls** [comment] 2020-09-29 01:09
closing as this is intentional by design

**Closed by Fuzzbawls** 2020-09-29 01:09 UTC
